### ISSUE TITLE
Blackhole service crash

### ISSUE THREAD

**Issue by ics** [DinoTools/dionaea#314]
##### ISSUE TYPE
 - Bug Report

##### DIONAEA VERSION
The issue is reproducible in these versions:
```
Dionaea Version 0.10.0
Compiled on Linux/x86_64 at Dec  8 2020 12:35:44 with gcc 8.3.0
Started on cesspit running Linux/x86_64 release 4.19.0-13-amd64
```
```
Dionaea Version 0.11.0
Compiled on Linux/x86_64 at Dec  8 2020 12:56:14 with gcc 8.3.0
Started on cesspit running Linux/x86_64 release 4.19.0-13-amd64
```

##### CONFIGURATION
Default configuration.

##### OS / ENVIRONMENT
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

##### SUMMARY
Dionea crashes when an instance of blackhole service is created.

##### STEPS TO REPRODUCE
Start dionaea with default config configuration.
Connect to any of the blackhole ports. e.g. `nc -nv ip 23`

##### EXPECTED RESULTS
No crash.

##### ACTUAL RESULTS
```
Dionaea Version 0.11.0
Compiled on Linux/x86_64 at Dec  8 2020 12:56:14 with gcc 8.3.0
Started on cesspit running Linux/x86_64 release 4.19.0-13-amd64

[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:581: glib version 2.58.3
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:585: libev api version is 4.25
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:600: libev backend is epoll
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:603: libev default loop 0x7f7316bf1720

[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:610: OpenSSL 1.1.1d  10 Sep 2019
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:624: udns version 0.4
[08122020 14:26:01] modules /root/dionaea/src/modules.c:101: loading module curl (lib/dionaea/curl.so)
[08122020 14:26:01] modules /root/dionaea/src/modules.c:101: loading module python (lib/dionaea/python.so)
[08122020 14:26:01] modules /root/dionaea/src/modules.c:101: loading module emu (lib/dionaea/emu.so)
[08122020 14:26:01] modules /root/dionaea/src/modules.c:160: configure module 0x55b21bd56f50
[08122020 14:26:01] modules /root/dionaea/src/modules.c:160: configure module 0x55b21bd59060
[08122020 14:26:01] modules /root/dionaea/src/modules.c:160: configure module 0x55b21bd59d30
[08122020 14:26:01] modules /root/dionaea/src/modules.c:172: configure module 0x55b21bd56f50
[08122020 14:26:01] modules /root/dionaea/src/modules.c:172: configure module 0x55b21bd59060
[08122020 14:26:01] modules /root/dionaea/src/modules.c:172: configure module 0x55b21bd59d30
[08122020 14:26:01] modules /root/dionaea/src/modules.c:197: new module lib/dionaea/curl.so 0x55b21bd56f50 fn 0x7f73165d5098
[08122020 14:26:01] curl /root/dionaea/modules/curl/module.c:638: curl version 7.64.0 features:c-ares,idn,ipv6,largefile,ntlm,spnego,ssl,libz protocols:dict,file,ftp,ftps,goph
er,http,https,imap,imaps,ldap,ldaps,pop3,pop3s,rtmp,rtsp,scp,sftp,smb,smbs,smtp,smtps,telnet,tftp
[08122020 14:26:01] modules /root/dionaea/src/modules.c:197: new module lib/dionaea/python.so 0x55b21bd59060 fn 0x7f73155aa585
[08122020 14:26:01] services /dionaea/services.py:114: Initializing services ...
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.blackhole
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.cmd
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.core
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.echo
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.emu
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.emu_scripts
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.exception
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.fail2ban
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.ftp
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.ftp_download
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.hpfeeds
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.http
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.ihandlers
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.log
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.log_db_sql
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.log_incident
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.log_json
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.logsql
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.memcache
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.mirror
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.mongo
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.mqtt
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.mssql
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.mysql
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.ndrlib
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.nfq
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.p0f
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.pptp
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.printer
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.pyev
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.s3
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.services
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.sip
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.smb
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.store
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.submit_http
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.submit_http_post
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.tftp
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.upnp
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.util
[08122020 14:26:01] dionaea /dionaea/__init__.py:148: Import module dionaea.virustotal
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:25: Load iHandlers
[08122020 14:26:01] modules /root/dionaea/src/modules.c:197: new module lib/dionaea/emu.so 0x55b21bd59d30 fn 0x7f7315021874
[08122020 14:26:01] processor /root/dionaea/src/processor.c:339: var/lib/dionaea/bistreams/2020-12-08/ <-> var/lib/dionaea/bistreams/%Y-%m-%d/
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:742: Using 1024 as limit for fds
[08122020 14:26:01] modules /root/dionaea/src/modules.c:184: start module 0x55b21bd56f50
[08122020 14:26:01] modules /root/dionaea/src/modules.c:184: start module 0x55b21bd59060
[08122020 14:26:01] python /root/dionaea/modules/python/module.c:293: start /root/dionaea/modules/python/module.c
[08122020 14:26:01] python /root/dionaea/modules/python/module.c:303: start dionaea.log 0x55b21bd46060 0x7f7314643e58
[08122020 14:26:01] python /root/dionaea/modules/python/module.c:303: start dionaea.services 0x55b21bd49510 0x7f73146560e8
[08122020 14:26:01] services /dionaea/services.py:164: Starting services ...
[08122020 14:26:01] services /dionaea/services.py:32: Starting services on interface enp0s4 ...
[08122020 14:26:01] services /dionaea/services.py:34: Bind interfaces to address '<redacted>' ...
[08122020 14:26:01] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:78: Starting cleanup loop
[08122020 14:26:01] services /dionaea/services.py:34: Bind interfaces to address 'fe80::2a0:98ff:fe7c:98e4' ...
[08122020 14:26:01] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] services /dionaea/services.py:32: Starting services on interface lo ...
[08122020 14:26:01] services /dionaea/services.py:34: Bind interfaces to address '127.0.0.1' ...
[08122020 14:26:01] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] services /dionaea/services.py:34: Bind interfaces to address '::1' ...
[08122020 14:26:01] pptp /dionaea/pptp/pptp.py:52: No config provided. Using default values
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] sip /dionaea/sip/__init__.py:575: SIP Session created with personality 'default'
[08122020 14:26:01] python /root/dionaea/modules/python/module.c:303: start dionaea.ihandlers 0x55b21bd434c0 0x7f731418bea8
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:36: START THE IHANDLERS
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:53: Starting <dionaea.log_json.LogJsonHandler object at 0x7f7312806808>
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:53: Starting <dionaea.tftp.tftpdownloadhandler object at 0x7f7314918608>
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:53: Starting <dionaea.store.storehandler object at 0x7f7312806888>
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:53: Starting <dionaea.cmd.cmdshellhandler object at 0x7f73128069c8>
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:53: Starting <dionaea.logsql.logsqlhandler object at 0x7f7312806a48>
[08122020 14:26:01] log_sqlite /dionaea/logsql.py:144: Getting RPC Services
[08122020 14:26:01] log_sqlite /dionaea/logsql.py:165: Setting RPC ServiceOps
[08122020 14:26:01] log_sqlite /dionaea/logsql.py:192: ... not required
[08122020 14:26:01] log_sqlite /dionaea/logsql.py:424: Setting MySQL Command Ops
[08122020 14:26:01] ihandlers /dionaea/ihandlers.py:53: Starting <dionaea.emu.emuprofilehandler object at 0x7f7312806ac8>
[08122020 14:26:01] modules /root/dionaea/src/modules.c:184: start module 0x55b21bd59d30
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:774: Installing signal handlers
[08122020 14:26:01] dionaea /root/dionaea/src/dionaea.c:811: Creating 2 threads in pool
[08122020 14:26:11] connection /root/dionaea/src/connection.c:2156: connection 0x55b21c4b1e10 none/tcp type: none->accept
[08122020 14:26:11] python /root/dionaea/modules/python/module.c:1039: AttributeError at 'Blackhole' object has no attribute 'apply_parent_config'
[08122020 14:26:11] python /root/dionaea/modules/python/module.c:1065: binding.pyx:749 in None
[08122020 14:26:11] python /root/dionaea/modules/python/module.c:1066:   dionaea.core._factory
```
Same crash occurs when running as root or when switching user.

**Comment by phibos** [comment]
Thanks for reporting the issue. I was able to reproduce it on Debian 10, but on Ubuntu 18.04 it works as expected.

* Debian 10 - Python 3.7
* Ubuntu 18.04 - Python 3.6

I will have a look at it in the next days.

**Comment by phibos** [comment]
I have found the issue. It's the ```proto``` argument in the ```__init__``` function. It has to be a ```kwarg``` with a default value. But cython and tracebacks seems to be a debugging nightmare when dealing with tracebacks.

But I don't know why it is working with Python 3.6 and not with Python 3.7.

I will fix the issue and try to detect and report the error.

**Comment by phibos** [comment]
The PR will be merged if all CI tests run successfully.

**Comment by phibos** [comment]
The fix has been merged and will be in the next release.

**Comment by ics** [comment]
Thanks for the fix, phibos!
It works for both Python 3.7 and 3.8.
